# Generated by Django 3.0.7 on 2023-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_auto_20230519_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas')], max_length=100),
        ),
    ]
