# Generated by Django 3.0.7 on 2023-05-19 18:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0012_auto_20230519_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Anti-Lock Braking System', 'Traction Control'), ('Off-road ABS', 'Rain Mode')], max_length=37),
        ),
    ]
