# Generated by Django 3.0.7 on 2023-05-19 19:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0013_auto_20230520_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ABS ', 'Anti-Lock Braking System'), ('Disc Brake', 'Disc Brake'), ('Off-Road ABS', 'Off-Road ABS'), ('Traction Control', 'Traction Control'), ('Rain Mode', 'Rain Mode'), ('Sport Mode', 'Sport Mode'), ('Economy Mode', 'Economy Mode'), ('FI-Engine', 'Fuel Injected Engine'), ('Carborator Engine', 'Carborator Engine')], max_length=107),
        ),
    ]
