# Generated by Django 3.0.7 on 2023-05-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0014_auto_20230520_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.IntegerField(choices=[(2022, 2022), (2023, 2023)], verbose_name='year'),
        ),
    ]
