# Generated by Django 3.2.18 on 2023-05-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0016_auto_20230521_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='milage',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='miles',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='no_of_owners',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='vin_no',
        ),
    ]
