# Generated by Django 3.2.18 on 2023-05-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0017_auto_20230521_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='transmission',
        ),
    ]
