# Generated by Django 3.2.18 on 2023-05-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0018_auto_20230521_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='transmission',
            field=models.CharField(default='manual', max_length=100),
        ),
    ]
