# Generated by Django 3.0.7 on 2023-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0004_spareparts_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spareparts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sparepartsorder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sparepartsreview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
